### ISSUE TITLE
Light mode or white text mode?

### ISSUE THREAD

**Issue by LordCrestfallen** [SOrdeal/Sordeal-Stealer#18]
I cannot read what the text says because it's practically the same color as the background. Is there a way for me to manually change the background in the PY file? Is there an option, or am I fucked?
![Screenshot 2023-04-24 123028](https://user-images.githubusercontent.com/131706299/234084710-6c0fe128-1eb6-4e26-a567-68d824e424b5.png)

**Comment by LordCrestfallen** [comment]
After looking at the screenshots, mine seems to be pitch black. Why is this happening?

**Comment by NolayDsc** [comment]
Hello, I will add the choice of theme on this new version so white / black

**Comment by LordCrestfallen** [comment]
> Hello, I will add the choice of theme on this new version so white / black (it will be added as soon as I am available in 1/2 days)

Alright, cool. Thanks, man.
