### ISSUE TITLE
ModuleNotFoundError: No module named 'pypresence'

### ISSUE THREAD

**Issue by jhoni409** [SOrdeal/Sordeal-Stealer#22]
I've tried to reinstall it, adding scripts to the path, everything(probabky) Any idea?

**Comment by ShamanOracle** [comment]
i don't see image

**Comment by jhoni409** [comment]
Here, 
![image](https://user-images.githubusercontent.com/77614696/235300070-abe424bd-7d86-412b-aee3-db37d0348c70.png)

**Comment by jhoni409** [comment]
Any ideas?

**Comment by sh4dowmanski** [comment]
open cmd with admin
type: pip install pypresence

does he say alr. installed, or does he install?
Or any error upon that, post it.

**Comment by jhoni409** [comment]
> open cmd with admin type: pip install pypresence
> 
> does he say alr. installed, or does he install? Or any error upon that, post it.

Says Requirement already satisfied: pypresence in, but still same error

**Comment by ShamanOracle** [comment]
patched
