### ISSUE TITLE
Webhook not working + warning

### ISSUE THREAD

**Issue by sh4dowmanski** [SOrdeal/Sordeal-Stealer#26]
The compressing and creating of the .exe file works fine.
The only issue I have is, that It wont give any information over webhook nor I do know what happens between.

I screenshot a message that will pop-up for a short moment:

[FILENAME].py:471: DeprecationWarning: Use setlocale(), getencoding() and getlocale() instead.

But so far the GUI of the tool looks amazing.

**Comment by ShamanOracle** [comment]
probably patched with latest
