### ISSUE TITLE
Keeps giving unknown Symbols..

### ISSUE THREAD

**Issue by Dragonov12333** [SOrdeal/Sordeal-Stealer#9]
when i tested the exe, it worked perfectly fine then when i created another exe file and enabled obfuscation mode, it kept giving me unknown symbols like :

â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯â€¯

In the System information like:

#â€¯Cookiesâ€¯Found:â€¯16
#â€¯Passwordsâ€¯Found:â€¯126
#â€¯Creditâ€¯Cardâ€¯Found:â€¯0
#â€¯Historyâ€¯Found:â€¯172
#â€¯Discordâ€¯Tokensâ€¯Found:â€¯0
#â€¯Robloxâ€¯Cookiesâ€¯Found:â€¯0
#â€¯Minecraftâ€¯Tokensâ€¯Found:â€¯0
#â€¯Wifiâ€¯Passwordsâ€¯Found:â€¯0

What the actual fuck is wrong with the obfuscation??

**Comment by ShamanOracle** [comment]
bruh my obfuscation don't like special characters i will fix it
